apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  labels:
    name: servicenodeport
  namespace: wordpress-namespace
spec:
  type: NodePort
  selector:
     app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
